---
ID: "6972ec98-a26f-4468-a968-35bae0e9ec4b"
Parent: "ca01cf7b-5298-466a-b25f-19b99f428f59"
Template: "ca01cf7b-5298-466a-b25f-19b99f428f59"
Path: /sitecore/templates/Project/Website/Page Types/Home Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{A2D8BADC-31FB-4EDF-B549-630EEB95CD64}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{AB53C8B6-7872-41EA-8780-C983665D993A}"
              s:ds=""
              s:par=""
              s:ph="home" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181122T130813Z
