---
ID: "84fbfc8b-87d6-43d4-8c6d-369d2fd7800a"
Parent: "15451229-7534-44ef-815d-d93d6170bfcb"
Template: "f1828a2c-7e5d-4bbd-98ca-320474871548"
Path: /sitecore/media library/Images/service
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/84FBFC8B87D643D48C6D369D2FD7800A.ashx?h=16&thn=1&w=16"
- ID: "22eac599-f13b-4607-a89d-c091763a467d"
  Hint: Width
  Value: 255
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "819d626b-cae8-4cc8-bcb5-668f2bb3a6c1"
  Value: iVBORw0KGgoAAAANSUhEUgAAAP8AAADFCAMAAACsN9QzAAAA0lBMVEX/wg//////wAD/vwD+67j/yz3/8M39wQD//v//997/1GL/xSX/4Jn/6a3/zk3//PAAAAD/9+b/1nP/2nv/1mz+5Jz/xRD/yRD/zRD/vAD/0hD+5aP+9t7+9Nf0vQ7+/vrpuA7+0Fn+xzH/7LtlTwb/35L+78a7lQs0JwP+24JMOAYFBgCshwqVdArWpw8KAwDJmwtCMARUPgWfeQogGgMcFAO3kwyEZAd0WgWWeQrOpAzOqA7tvQ7AmwtdRgaLbAf/3hEsIQHfsQ06LQQoHAJvVwi5im8MAAAJjUlEQVR4nO2dCV/iPBCHS4IGQSWKppSjHB6oC16I7roqC+r3/0pvrhbQHuxrm4I7//2tIrRNnsxkclAGywKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCBQpBBBZkUQRllD+yJsIwtljW0xJn9htpnLQK3dzD1A8qONZhb4uXLm/AKf4VI5E/wV4BfCB41cgdem9W/y43Pj3CvET9COrEpB/sx3iqmrU/eLy5yfEXwo6VV9ctsOTlMIYezslzV91vw89uHuka7Kzp6o1SFOuUyEt1fI//HGnqpI6wTvCSc4dNItEJEd7fx7rez58a437hUdJlsiZX7EvHlGvZghP1P/caeljFGuOBYxwE+6mzrUnuP9zO2Pt/WA39jlvd4Av7PbUL7fOncy5yeiJxZEdU4ZEn+mzM8sVNG9bY+3N8qYn+C8dsVNQkTtUre/U9EFNja4u2Vsf+T3xB1E5DNp8+MTHfmaJcGM9rMc//Dulp7ynHsVSDf+q3FPmPyoJNsbZ8bPAz8qlnXg72C9Ak6XH3WbsrxC7gQjueeQZf8XM1Bu/kKu1ZkVnyY/Zk0da7e9+WWG/P56r8kDEdPmT5Mfi3FPzjIrWJeWHT/S6z3RE+cLT48fHbT0lLc4KzArfmJ5C548Ql7fF0qN3/HcrdGdW1xlxI95ICrI0F/n4x6beyUtfnSiJ9nN7jxrNvyz9d45JosvpcOPsOxtvMFPSwsFZsKvJl05Pe4tKgV+PuXtbinjt04+vNeRBT+utNTOi48/1wHSsD8qee8qnOhZpl+geX6iXZH3RBKwy5MCv7+90Kp8uqxxfuJvPJ2Wgja5kufHRS/YFD8XaJoflbydlx0UWGbi/Fiu97i/NYPa2zA/2m3qtzfOQ0pMmh8f6li7OO75FTLKjze8nriPF0b9mZLln+1znlqBiEb58cGeDvwHOJje509m/xuVTnV714PxjfLPth42wvFIgvxYDvty3AvzJ2P8zNKuWMgdWU7YvRgYe/s/GOEv3teBcUdvL4jeljU/n4BrW7ROtiN0KCPEZuQxS6peVnsdvLeF18oYvz/tMSm53C1hKyTYGuYvLMdfmPv5df5mNyqWmLb/39U9Afyj6Ju7zPIXjN7aIRowT6LJTPt/aytajYZsorJ4FHNonGQb7MdMpAzbP9ewSjGS41899rBYWdL+ldCJVhb8uVwjoiDC/6Gk5j8ISftXYi5kmn8rrqDE5v+ryR9lfyngB37gB/4vlwf8wA/8wB9z1HrzR0zu/wn+oAvoNvk3+Bn7/Ejp2/PP3TMS1A2+Az/TZIzN2XnuWDZ/wOyh/L3e/KLazJ4+PlXFk20uVlWvT/Vd4xarus+957Z42m1LqXN+t21x4Nrzs+nx6Opt6FrMvZ28vV0MJNbTxdSz8/CVUjoZuJbde+MH3N1y07ffR3QyFEesNz/3f/uGPtzf0ktmuWd0MPhB+zY37zX9KduBuS/0td+7f6dTZt/Ti+Fg0GdW9YWf80Kf2frzsza9YbYrrO2ejezqNT3mD6vHdCQdoDqmx0821zW3/z19qMl+z+hVTZ2z/vwuvZvWbMYd3X29q9Yu6Qt/PKXHnJUf1r6jqp/zIzj/+E+1yiOBTWm7pgLguvNb9i86Gk5t4epnP/rDifB/++eofUvbHLlHX6reLdOcf3Q2mXD/qPYpHU+/QfwT45/dG1HKOzW3Pw90V2Nbmv/PI+WRkPXpQ1WfIez/dnFz887EOVf0x7C69v1fVtu2f03ovc37/4XNhHtX3+lDr39282SxZ2F/Le4M4z+1WlWdc39Gh7aF15vfEW7N/fmZvtc4/01VjvjTOyrVs1l7RF3V/y0Z/3RjiHN69NZed/s7ln3587pWe6Q/Fb94zX6gvx4fH3+PJrZVHdDbNo957tAV/X9c40MBj4riHO4a34CfXdK78eCMXttM8/MR8VWMeLUBD4XMfaeT8XB8Q9vC/pPjl5cHPlLwMPHrVUTK9ee3+z+4qw9E/OP9n79k92lftsPl1S2fFdpD2RvGcjAQuhC+fyWeEkevOz/nda+v1Rjvupb6pRc/6m/bvexdqyDw5D658knmXve+w/xfrv+YbesR3nvxw8H89U9LX++cb8D/V/rYEN+Bf26LI2qrL1Dfgf8rAn7gB37gjzkK+IEf+IH/y+XFCfiX4WeJ5f/w+SMnzubynyxpf8W/7aAvJzmT/PvRidSQs2L8WPn/UfHgqypK/nrMhYoy7dzq8Av7FxL7kMyyF1oZfuR/XDMZ/CUbYFX4Z0lBEmyD9eEn1uayNV4SPOZa3geyVoBfJoHcNPwBOa+vmch/HGt/P01BeZ+wBCSvVUHhBxCW1y6QJ6G1MsaPix7+Aba++NFXKcXvkMCLWeLzsac6ROat7PllNihRm63Izysur7j5L+6obMsiB00iBcYolF/erEFkMl4vPc/f7vUGKYpfJt30UhF8zkGTiqLsj4iXDeroYz6g/61o+6t5P2/wciflVLN+ieH8iMk0BTIbVELWj+HHJzr078nelkyJ0Qr3f5EMS7nioZNcIIrgJ6iu3S0fmBQkFYXy44Oysn6rmGQYDucnlh/4DX7zRRg/PvCTYSWb9CmMf5YNqm6OPpQfny/0xOQUws9m2aDMjHueAvl5T2ypeehm0j0xhN/pLJEVIw0F8ZOSH/gTG/c8BfP7STcbETloUlEAP1KBKJcGfjC/n3xsyzT+Z36GNvy0dCT5CXgAP/FzcJwiAzP+RX3i9xc8e/tpxOHP/Kirs0HldkwseD7oI79T8QJ/Oq74iR939YInd+KYHPi84hf5kQpEBR6I0qnMR37c8dIAhmeDSlML/PLrNwqF2PQ8X9AHfrzr4Rse9zzN57+YZUGspzYDXeAn6FAPtKm1d5wUf1PgEiI3+lqFNGegC/zYW/BsBibdNKGZ/4vsv2rnJTQtXQKa45fb6jLa5s2Pe558frHx1Eq/J874MTvyvlYqJAuiCWl+or5xQAb+VF3R558L/I6RnY5g6f7veDsvjZQDkcePNrz1dUaBX0vnvzr0ZqCllF2RyHBfcQ7KH5JNZ6RZ/ruCkRkoUfY/99K+72aLP+MX+NsJbvSFSPn/nuduLGN87f+Snwd+RBBJVyg392ZiHhMzu7xL8POueLppQLmZdmKyIJriNy/R4uVzQ29xRCo7/qy/3FIpG37xLWerYP3M+BsbKDA9iHGhylHeuI7qaU+zlpfp73UXwgithPFBIBAIBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQCAQCAQCgbLXf1+zEBTII6gjAAAAAElFTkSuQmCC
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 2724
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: image/png
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: png
- ID: "cb09946f-3218-4823-87d2-d5007c199a96"
  Hint: Dimensions
  Value: 255 x 197
- ID: "de2ca9e4-c117-4c8a-a139-1ff4b199d15a"
  Hint: Height
  Value: 197
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181124T201256Z
