---
ID: "842e4502-dfbf-494b-a0c6-ab341626c56e"
Parent: "d344340d-8183-4fb3-ae55-464843673f43"
Template: "a2d8badc-31fb-4edf-b549-630eeb95cd64"
Path: /sitecore/content/Home/Services
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{45CF24E2-A40F-4893-807B-0AB0195B8AAA}"
          s:ds="{D344340D-8183-4FB3-AE55-464843673F43}" />
        <r
          uid="{486AAD17-2AC5-4525-85BD-011E5BDB9122}"
          s:ds="{4AD4D48B-5E94-4D4A-81F4-33FE5D0EE3EF}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <p
              uid="{CABB5C24-F1FA-4EED-BDFE-EB29891C868D}"
              p:before="*"
              s:key="main"
              s:md="{5A4F82E5-1141-4025-8214-F0C111CA3702}" />
            <r
              uid="{D27028CA-2CC7-492F-B067-85BDD1AEC93E}"
              p:after="p[@uid='{CABB5C24-F1FA-4EED-BDFE-EB29891C868D}']"
              s:id="{4DFB758F-AB5F-4F2B-AB32-58B5DE674D54}"
              s:ph="/top/home" />
            <r
              uid="{99DD87F6-3808-4947-B9C1-AB425BCC59D6}"
              p:after="r[@uid='{D27028CA-2CC7-492F-B067-85BDD1AEC93E}']"
              s:id="{C3555FA0-0E14-4B5B-BF07-E770887847C3}"
              s:ph="main" />
            <r
              uid="{AB53C8B6-7872-41EA-8780-C983665D993A}">
              <p:d />
            </r>
            <r
              uid="{486AAD17-2AC5-4525-85BD-011E5BDB9122}"
              s:ds="{4AD4D48B-5E94-4D4A-81F4-33FE5D0EE3EF}" />
            <r
              uid="{F90304F7-D380-4816-A7FD-71C8A8B575E7}"
              s:ds="{D344340D-8183-4FB3-AE55-464843673F43}"
              s:par="" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181126T084552Z
    - ID: "781e9acf-2f70-493c-bf12-55c66ea84181"
      Hint: Title
      Value: Services
    - ID: "de1f2951-6d67-4a37-a2ba-38e0543158ff"
      Hint: Description
      Value: |
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        
    - ID: "fdee4d8e-dce5-4e83-9219-dc5657e4c88e"
      Hint: Banner
      Value: |
        <image mediaid="{2A716BEB-144D-47C9-8CF5-55CE38053FE5}" />
